'use strict';
/* NexaDesk AI mockup: all data is local and resets on reload. No backend. */
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ST=['Open','Pending','Resolved','Closed'],PR=['Low','Medium','High','Urgent'],CA=['Billing','Technical','Account','Refund','General'];
const agents=[{n:'Priya Nair',r:'Admin',on:1},{n:'Arjun Mehta',r:'Agent',on:1},{n:'Sara Khan',r:'Agent',on:1},{n:'Rohan Patil',r:'Agent',on:0}];
const custs=[{n:'Ananya Rao',e:'ananya@brightlabs.io',co:'Bright Labs'},{n:'Mark Ellis',e:'mark@ellisandco.com',co:'Ellis & Co'},{n:'Neha Joshi',e:'neha@zenfoods.in',co:'Zen Foods'},{n:'Tom Becker',e:'tom@northwind.dev',co:'Northwind'},{n:'Isha Kapoor',e:'isha@loomstudio.co',co:'Loom Studio'},{n:'Luis Ortega',e:'luis@cobaltpay.com',co:'CobaltPay'}];
const tix=[['Refund for duplicate charge',0,'Refund','High','Open',1],['Cannot reset my password',1,'Account','Medium','Open',-1],['API returns 500 on export',3,'Technical','Urgent','Pending',2],['Invoice missing GST number',2,'Billing','Medium','Resolved',1],['How do I add a teammate?',4,'General','Low','Resolved',2],['Dashboard loads slowly',5,'Technical','High','Open',1],['Change billing email',0,'Billing','Low','Closed',0],['Two-factor code not arriving',1,'Account','High','Pending',2],['Upgrade plan mid-cycle',2,'Billing','Medium','Open',-1],['Webhook retries failing',3,'Technical','High','Open',1],['Cancel subscription and refund',4,'Refund','Medium','Pending',2],['Feature request: dark mode',5,'General','Low','Open',-1],['Login loop on Safari',0,'Technical','Medium','Resolved',1],['Update company name on invoices',2,'Billing','Low','Closed',0]]
.map((x,i)=>({id:'NX-'+(1001+i),s:x[0],c:x[1],cat:x[2],pri:x[3],st:x[4],ag:x[5],age:i*5+1,msgs:[{w:'c',t:`Hi, ${x[0].toLowerCase()}. Could you please help? Thanks.`,tm:ago(i*5+1)}],log:['Ticket created by customer']}));
function ago(h){return h<48?h+'h ago':Math.round(h/24)+'d ago'}
const S={role:'admin',view:'dash',id:null,pg:1,q:'',f:{st:'',pri:'',cat:'',ag:''},so:'new',sel:new Set(),mode:'reply',dr:'',cs:0,cq:'',tab:'Profile',aiId:null};
const NAV=[['dash','Dashboard'],['inbox','Ticket Inbox'],['new','Create Ticket'],['cust','Customers'],['team','Team'],['ai','AI Assistant'],['stats','Analytics'],['set','Settings']];
const curNav=()=>S.role==='customer'?[['dash','Dashboard'],['inbox','My Tickets'],['new','Submit Ticket']]:S.role==='staff'?NAV.filter(n=>n[0]!=='team'):NAV;
const find=id=>tix.find(t=>t.id===id),fn=i=>i<0?'Unassigned':agents[i].n,cnt=s=>tix.filter(t=>t.st===s).length;
const bd=(k,x)=>`<span class="b ${k}-${x}">${x}</span>`;
const opts=(a,sel,all)=>(all!=null?`<option value="">${all}</option>`:'')+a.map(x=>`<option${x===sel?' selected':''}>${x}</option>`).join('');
const agOpts=sel=>`<option value="-1"${sel==-1?' selected':''}>Unassigned</option>`+agents.map((a,i)=>`<option value="${i}"${sel===String(i)||sel===i?' selected':''}>${esc(a.n)}</option>`).join('');
const sug=t=>{const f=custs[t.c].n.split(' ')[0];return{Refund:`Hi ${f}, I'm sorry for the trouble. I've started a review of your refund request and will confirm the outcome within 2 business days.`,Technical:`Hi ${f}, thanks for the details. Our engineers are investigating and I'll update you as soon as we have a fix or workaround.`,Billing:`Hi ${f}, I've checked your billing record and will send a corrected invoice shortly.`,Account:`Hi ${f}, I've sent a secure link to your registered email so you can regain access. Tell me if it doesn't arrive.`,General:`Hi ${f}, thanks for reaching out. Here is how to do that, and I'm happy to walk you through it.`}[t.cat]};
const conf=t=>70+(+t.id.slice(3)*7)%28;
const sum=t=>`${custs[t.c].n} (${custs[t.c].co}) reports: "${t.s}". Looks like a ${t.cat} issue, priority ${t.pri}. ${t.msgs.length} message(s) so far.`;
const bars=(v,l)=>{const m=Math.max(...v);return`<div class="bars" role="img" aria-label="Bar chart: ${l.map((x,i)=>x+' '+v[i]).join(', ')}">${v.map((n,i)=>`<div class="bar"><i style="height:${n/m*100}%"></i><b>${n}</b><small>${l[i]}</small></div>`).join('')}</div>`};
const meter=(p,l)=>`<div class="row"><span>${l}</span><span>${p}%</span></div><div class="meter" role="img" aria-label="${l} ${p}%"><i style="width:${p}%"></i></div>`;
const tbl=(l,chk)=>`<div class="tw"><table><thead><tr>${chk?'<th><input type="checkbox" data-act="selall" aria-label="Select all on page"></th>':''}<th>ID</th><th>Subject</th><th>Customer</th><th>Category</th><th>Priority</th><th>Status</th><th>Agent</th><th>Updated</th></tr></thead><tbody>${l.length?l.map(t=>`<tr>${chk?`<td><input type="checkbox" data-act="sel" data-id="${t.id}" aria-label="Select ${t.id}"${S.sel.has(t.id)?' checked':''}></td>`:''}<td>${t.id}</td><td><a href="#" data-act="open" data-id="${t.id}">${esc(t.s)}</a></td><td>${esc(custs[t.c].n)}</td><td>${t.cat}</td><td>${bd('p',t.pri)}</td><td>${bd('s',t.st)}</td><td>${esc(fn(t.ag))}</td><td>${ago(t.age)}</td></tr>`).join(''):'<tr><td colspan="9" class="empty">No tickets match your filters.</td></tr>'}</tbody></table></div>`;
function toast(m,bad){const d=document.createElement('div');d.className='toast'+(bad?' bad':'');d.textContent=m;$('#toasts').append(d);setTimeout(()=>d.remove(),3200)}
function fe(id,m){const e=$('#e-'+id);if(e)e.textContent=m||'';const i=$('#'+id);if(i)i.setAttribute('aria-invalid',!!m);return!m}
const mailOk=x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x);
function modal(title,html,ok){const d=$('#dlg');d.innerHTML=`<form id="mf" novalidate><h2 id="dt">${title}</h2>${html}<div class="row end"><button type="button" class="btn ghost" data-act="close">Cancel</button><button class="btn">Save</button></div></form>`;$('#mf').onsubmit=e=>{e.preventDefault();if(ok())d.close()};d.showModal()}
const v={};
v.dash=()=>{const cc=CA.map(c=>tix.filter(t=>t.cat===c).length),col=['#2563eb','#0ea5a4','#f59e0b','#e11d48','#64748b'];let a=0;const g=cc.map((n,i)=>{const s=a;a+=n/tix.length*100;return`${col[i]} ${s}% ${a}%`}).join(',');
return`<h1>Dashboard</h1><div class="grid g5">${[['Total tickets',tix.length],['Open',cnt('Open')],['Pending',cnt('Pending')],['Resolved',cnt('Resolved')],['Avg first response','1h 42m']].map(x=>`<div class="card stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>
<div class="grid g2"><section class="card"><h2>Ticket trends, last 7 days</h2>${bars([12,18,15,22,19,9,14],['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])}</section>
<section class="card"><h2>Distribution by category</h2><div class="dwrap"><div class="donut" role="img" aria-label="Category distribution" style="background:conic-gradient(${g})"></div><ul>${CA.map((c,i)=>`<li><i style="background:${col[i]}"></i>${c}: ${cc[i]}</li>`).join('')}</ul></div></section></div>
<div class="grid g2"><section class="card"><h2>Recent activity</h2><ul class="feed">${tix.slice(0,5).map(t=>`<li><b>${t.id}</b> ${esc(t.log[0])}</li>`).join('')}</ul></section><section class="card"><h2>Recent tickets</h2>${tbl(tix.slice(0,4),0)}</section></div>`};
function filt(){const q=S.q.toLowerCase(),l=tix.filter(t=>(!q||(t.id+t.s+custs[t.c].n).toLowerCase().includes(q))&&(!S.f.st||t.st===S.f.st)&&(!S.f.pri||t.pri===S.f.pri)&&(!S.f.cat||t.cat===S.f.cat)&&(S.f.ag===''||String(t.ag)===S.f.ag));
return l.sort(S.so==='pri'?(a,b)=>PR.indexOf(b.pri)-PR.indexOf(a.pri):S.so==='old'?(a,b)=>b.age-a.age:(a,b)=>a.age-b.age)}
const inboxBody=()=>{const l=filt(),n=Math.max(1,Math.ceil(l.length/6));S.pg=Math.min(S.pg,n);return`${S.sel.size?`<div class="bulk">${S.sel.size} selected <button class="btn sm" data-act="bres">Mark resolved</button><button class="btn ghost sm" data-act="bclr">Clear</button></div>`:''}${tbl(l.slice((S.pg-1)*6,S.pg*6),1)}<div class="pager"><span>${l.length} tickets</span><span><button class="btn ghost sm" data-act="pg" data-d="-1"${S.pg<2?' disabled':''}>Previous</button> Page ${S.pg} of ${n} <button class="btn ghost sm" data-act="pg" data-d="1"${S.pg>=n?' disabled':''}>Next</button></span></div>`};
const upd=()=>{$('#tb').innerHTML=inboxBody()};
v.inbox=()=>`<h1>Ticket Inbox</h1><div class="card"><div class="filters"><label>Search<input type="search" data-inp="q" value="${esc(S.q)}" placeholder="ID, subject, customer"></label>
<label>Status<select data-chg="f" data-k="st">${opts(ST,S.f.st,'All')}</select></label><label>Priority<select data-chg="f" data-k="pri">${opts(PR,S.f.pri,'All')}</select></label><label>Category<select data-chg="f" data-k="cat">${opts(CA,S.f.cat,'All')}</select></label>
<label>Agent<select data-chg="f" data-k="ag"><option value="">All</option>${agOpts(S.f.ag)}</select></label><label>Sort by<select data-chg="f" data-k="so"><option value="new"${S.so==='new'?' selected':''}>Newest</option><option value="old"${S.so==='old'?' selected':''}>Oldest</option><option value="pri"${S.so==='pri'?' selected':''}>Priority</option></select></label></div><div id="tb">${inboxBody()}</div></div>`;
v.tk=()=>{const t=find(S.id),c=custs[t.c];return`<p><a href="#" data-act="go" data-v="inbox">&larr; Back to inbox</a></p><div class="grid gd"><div>
<section class="card"><p class="mut">${t.id}</p><h1>${esc(t.s)}</h1><div class="meta"><label>Status<select data-chg="st">${opts(ST,t.st)}</select></label><label>Priority<select data-chg="pri">${opts(PR,t.pri)}</select></label><label>Assigned agent<select data-chg="ag">${agOpts(t.ag)}</select></label></div></section>
<section class="card"><h2>Conversation</h2><ol class="tl">${t.msgs.map(m=>`<li class="m-${m.w}"><b>${m.w==='c'?esc(c.n):m.w==='n'?'Internal note (agents only)':'You'}</b> <small class="mut">${m.tm}</small><p>${esc(m.t)}</p></li>`).join('')}</ol></section>
<section class="card"><div class="tabs" role="tablist">${[['reply','Reply'],['note','Internal note']].map(x=>`<button role="tab" class="${S.mode===x[0]?'on':''}" aria-selected="${S.mode===x[0]}" data-act="mode" data-m="${x[0]}">${x[1]}</button>`).join('')}</div>
<label for="cmp" class="sr">Message</label><textarea id="cmp" rows="4" class="${S.mode==='note'?'note':''}" placeholder="${S.mode==='note'?'Only agents can see this note':'Write a reply to the customer'}">${esc(S.dr)}</textarea>
<div class="row end"><button class="btn ghost" data-act="ins">Use AI suggestion</button><button class="btn" data-act="send">${S.mode==='note'?'Add note':'Send reply'}</button></div></section></div>
<div><section class="card"><h2>Customer</h2><p><b>${esc(c.n)}</b><br>${esc(c.e)}<br>${esc(c.co)}</p></section><section class="card ai"><h2>AI summary</h2><p>${esc(sum(t))}</p></section>
<section class="card ai"><h2>AI suggested reply</h2><p>${esc(sug(t))}</p><p class="mut sm">Mock text. Always review before sending.</p></section><section class="card"><h2>Activity history</h2><ul class="feed" id="hist">${hist(t)}</ul></section></div></div>`};
const hist=t=>t.log.map(x=>`<li>${esc(x)}</li>`).join('');
const logc=(t,m)=>{t.log.unshift(m);$('#hist').innerHTML=hist(t);toast(m)};
v.new=()=>`<h1>Create Ticket</h1><form class="card" id="nf" novalidate><label for="ce">Customer email</label><input id="ce" type="email"><small class="err" id="e-ce"></small>
<label for="cs2">Subject</label><input id="cs2"><small class="err" id="e-cs2"></small><label for="cd">Description</label><textarea id="cd" rows="5"></textarea><small class="err" id="e-cd"></small>
<div class="grid g2"><div><label for="cc">Category</label><select id="cc">${opts(CA)}</select></div><div><label for="cp">Priority</label><select id="cp">${opts(PR,'Medium')}</select></div></div>
<label for="cf">Attachments</label><div class="drop"><input id="cf" type="file" multiple data-chg="files"><small class="mut">Max 5 MB each. Files stay in your browser and are not uploaded.</small><small class="err" id="e-cf"></small><ul class="feed" id="fl"></ul></div><div class="row end"><button class="btn">Create ticket</button></div></form>`;
const custList=()=>custs.map((c,i)=>({c,i})).filter(x=>(x.c.n+x.c.e+x.c.co).toLowerCase().includes(S.cq.toLowerCase())).map(x=>`<li><button class="${S.cs===x.i?'on':''}" data-act="cus" data-i="${x.i}">${esc(x.c.n)}<small>${esc(x.c.co)}</small></button></li>`).join('')||'<li class="empty">No customers found.</li>';
const custProf=()=>{const c=custs[S.cs],l=tix.filter(t=>t.c===S.cs);return`<h2>${esc(c.n)}</h2><p>${esc(c.e)}, ${esc(c.co)}</p><h3>Ticket history (${l.length})</h3>${tbl(l,0)}`};
v.cust=()=>`<h1>Customers</h1><div class="grid gc"><section class="card"><label for="cq">Search customers</label><input id="cq" type="search" data-inp="cq" value="${esc(S.cq)}"><ul class="list" id="cl">${custList()}</ul></section><section class="card" id="cpf">${custProf()}</section></div>`;
v.team=()=>`<div class="row"><h1>Team Management</h1><button class="btn" data-act="inv">Invite agent</button></div><div class="card tw"><table><thead><tr><th>Name</th><th>Role</th><th>Status</th><th><span class="sr">Actions</span></th></tr></thead><tbody>${agents.map((a,i)=>`<tr><td>${esc(a.n)}</td><td>${a.r}</td><td>${bd('s',a.on===2?'Invited':a.on?'Active':'Inactive')}</td><td>${a.r==='Admin'?'':`<button class="btn ghost sm" data-act="tog" data-i="${i}">${a.on===1?'Deactivate':'Activate'}</button>`}</td></tr>`).join('')}</tbody></table></div>`;
v.ai=()=>{const t=find(S.aiId||tix[0].id),k=conf(t);S.aiId=t.id;return`<h1>AI Assistant</h1><section class="card"><label for="at">Ticket</label><select id="at" data-chg="ai">${tix.map(x=>`<option value="${x.id}"${x.id===t.id?' selected':''}>${x.id}: ${esc(x.s)}</option>`).join('')}</select></section>
<div class="grid g2"><section class="card ai"><h2>Classification</h2><p>${bd('c',t.cat)} ${bd('p',t.pri)}</p>${meter(k,'Confidence')}<h2 style="margin-top:14px">Summary</h2><p>${esc(sum(t))}</p></section>
<section class="card ai"><h2>Suggested response</h2><p>${esc(sug(t))}</p><p class="mut sm">Decision: ${t.ai||'pending'}. Replies are never sent automatically.</p><div class="row end"><button class="btn ghost" data-act="rej">Reject</button><button class="btn" data-act="acc">Accept</button></div></section></div>`};
v.stats=()=>{const pts=[5.2,4.8,4.9,4.1,3.7,3.2].map((p,i)=>`${12+i*54},${110-p/6*100}`).join(' ');
return`<h1>Analytics</h1><div class="grid g2"><section class="card"><h2>Ticket volume, last 6 weeks</h2>${bars([64,71,58,83,77,69],['W1','W2','W3','W4','W5','W6'])}</section>
<section class="card"><h2>Average resolution time (hours)</h2><svg viewBox="0 0 290 130" role="img" aria-label="Resolution time falling from 5.2 to 3.2 hours"><polyline fill="none" stroke="#2563eb" stroke-width="3" points="${pts}"/></svg><p class="mut sm">Sample trend data, weeks 1 to 6.</p></section></div>
<div class="grid g2"><section class="card"><h2>Agent performance</h2><div class="tw"><table><thead><tr><th>Agent</th><th>Assigned</th><th>Resolved</th></tr></thead><tbody>${agents.slice(0,3).map((a,i)=>`<tr><td>${esc(a.n)}</td><td>${tix.filter(t=>t.ag===i).length}</td><td>${tix.filter(t=>t.ag===i&&t.st==='Resolved').length}</td></tr>`).join('')}</tbody></table></div></section>
<section class="card"><h2>Priority distribution</h2>${PR.map(p=>meter(Math.round(tix.filter(t=>t.pri===p).length/tix.length*100),p)).join('')}</section></div>`};
const chk=a=>a.map((x,i)=>`<label class="chk"><input type="checkbox"${i<2?' checked':''}> ${x}</label>`).join('');
const setTabs={Profile:'<label for="sn">Full name</label><input id="sn" value="Priya Nair"><label for="se">Email</label><input id="se" type="email" value="priya@nexadesk.example">',
Team:'<label for="tn">Workspace name</label><input id="tn" value="NexaDesk Support"><label for="tz">Time zone</label><select id="tz"><option>Asia/Kolkata</option><option>UTC</option><option>Europe/London</option></select>',
Notifications:chk(['Ticket assigned to me','Customer replied','Daily summary','Weekly report']),
Email:'<label for="sa">Support address</label><input id="sa" type="email" value="support@nexadesk.example"><label for="sg">Signature</label><textarea id="sg" rows="3">Best regards,\nNexaDesk Support</textarea><p class="mut sm">Email provider connection is not part of this mockup.</p>',
AI:chk(['Suggest category and priority','Write ticket summaries','Suggest replies'])+'<label class="chk"><input type="checkbox" disabled> Auto-send replies (off: humans review)</label><label for="th">Minimum confidence: <output id="tho">80</output>%</label><input id="th" type="range" min="50" max="99" value="80" data-inp="th">'};
v.set=()=>`<h1>Settings</h1><div class="tabs" role="tablist">${Object.keys(setTabs).map(k=>`<button role="tab" class="${S.tab===k?'on':''}" aria-selected="${S.tab===k}" data-act="tab" data-t="${k}">${k}</button>`).join('')}</div><form class="card" id="sf">${setTabs[S.tab]}<div class="row end"><button class="btn">Save changes</button></div></form>`;
function render(){$('#main').innerHTML=v[S.view]();$('#nav').innerHTML=curNav().map(n=>`<button data-act="go" data-v="${n[0]}" class="${n[0]===S.view||(S.view==='tk'&&n[0]==='inbox')?'on':''}"${n[0]===S.view?' aria-current="page"':''}>${n[1]}</button>`).join('')}
function go(view,id){S.view=view;if(id)S.id=id;$('#side').classList.remove('open');render();$('#main').focus()}
const act={go:a=>go(a.dataset.v),open:a=>go('tk',a.dataset.id),menu:()=>$('#side').classList.toggle('open'),close:()=>$('#dlg').close(),
role:a=>{const r=a.dataset.r;S.role=r;$$('[data-act=role]').forEach(b=>b.classList.toggle('on',b===a));if(r==='customer'){$('#um-btn').innerHTML='Sarah Chen &#9662;';toast('Switched to Customer role (Sarah Chen)')}else if(r==='staff'){$('#um-btn').innerHTML='Marcus Vance &#9662;';toast('Switched to Staff role (Marcus Vance)')}else{$('#um-btn').innerHTML='Priya Nair &#9662;';toast('Switched to Admin role (Priya Nair)')}go('dash')},
lrole:a=>{const r=a.dataset.r;S.role=r;$$('[data-act=lrole]').forEach(b=>b.classList.toggle('on',b===a));if(r==='customer'){$('#em').value='sarah.chen@acme.com'}else if(r==='staff'){$('#em').value='marcus.vance@nexadesk.internal'}else{$('#em').value='admin@nexadesk.internal'}},
um:a=>{const m=$('#umm');m.hidden=!m.hidden;a.setAttribute('aria-expanded',!m.hidden)},prof:()=>{$('#umm').hidden=true;S.tab='Profile';go('set')},
out:()=>{$('#umm').hidden=true;$('#app').hidden=true;$('#login').hidden=false},forgot:()=>toast('A reset link would be emailed here (mock).'),
sel:a=>{a.checked?S.sel.add(a.dataset.id):S.sel.delete(a.dataset.id);upd()},selall:a=>{$$('[data-act=sel]').forEach(c=>a.checked?S.sel.add(c.dataset.id):S.sel.delete(c.dataset.id));upd()},
bres:()=>{S.sel.forEach(i=>{const t=find(i);t.st='Resolved';t.log.unshift('Status changed to Resolved (bulk)')});toast(S.sel.size+' tickets resolved');S.sel.clear();upd()},bclr:()=>{S.sel.clear();upd()},
pg:a=>{S.pg+=+a.dataset.d;upd()},mode:a=>{S.dr=$('#cmp').value;S.mode=a.dataset.m;render()},ins:()=>{$('#cmp').value=sug(find(S.id))},
send:()=>{const x=$('#cmp').value.trim();if(!x)return toast('Write a message first.',1);const t=find(S.id),n=S.mode==='note';t.msgs.push({w:n?'n':'a',t:x,tm:'just now'});t.log.unshift(n?'Internal note added':'Reply sent to customer');S.dr='';render();toast(n?'Note added':'Reply sent (mock)')},
cus:a=>{S.cs=+a.dataset.i;$('#cl').innerHTML=custList();$('#cpf').innerHTML=custProf()},
inv:()=>modal('Invite agent','<label for="ie">Email</label><input id="ie" type="email"><small class="err" id="e-ie"></small><label for="ir">Role</label><select id="ir"><option>Agent</option><option>Admin</option></select>',()=>{const e=$('#ie').value.trim();if(!fe('ie',mailOk(e)?'':'Enter a valid email address.'))return false;agents.push({n:e,r:$('#ir').value,on:2});render();toast('Invitation recorded (mock, no email sent)');return true}),
tog:a=>{const g=agents[+a.dataset.i];g.on=g.on===1?0:1;render();toast(g.n+(g.on?' activated':' deactivated'))},
acc:()=>{const t=find(S.aiId);t.ai='accepted';t.log.unshift('AI suggestion accepted');S.dr=sug(t);render();toast('Accepted. Added to the reply draft of '+t.id)},rej:()=>{const t=find(S.aiId);t.ai='rejected';t.log.unshift('AI suggestion rejected');render();toast('Suggestion rejected')},
tab:a=>{S.tab=a.dataset.t;render()}};
document.addEventListener('click',e=>{const a=e.target.closest('[data-act]');if(!a||!act[a.dataset.act])return;if(a.tagName==='A')e.preventDefault();act[a.dataset.act](a,e)});
const chg={f(el){S.f[el.dataset.k]=el.value;if(el.dataset.k==='so')S.so=el.value;S.pg=1;upd()},
st(el){find(S.id).st=el.value;logc(find(S.id),'Status changed to '+el.value)},pri(el){find(S.id).pri=el.value;logc(find(S.id),'Priority changed to '+el.value)},ag(el){find(S.id).ag=+el.value;logc(find(S.id),'Assigned to '+fn(+el.value))},
ai(el){S.aiId=el.value;render()},files(el){const ok=[...el.files].filter(f=>f.size<=5242880);fe('cf',ok.length<el.files.length?'Some files exceed 5 MB and were skipped.':'');$('#fl').innerHTML=ok.map(f=>`<li>${esc(f.name)} (${Math.ceil(f.size/1024)} KB)</li>`).join('')}};
document.addEventListener('change',e=>{const k=e.target.dataset.chg;if(k&&chg[k])chg[k](e.target)});
document.addEventListener('input',e=>{const k=e.target.dataset.inp;if(k==='q'){S.q=e.target.value;S.pg=1;upd()}else if(k==='cq'){S.cq=e.target.value;$('#cl').innerHTML=custList()}else if(k==='th')$('#tho').textContent=e.target.value});
$('#gs').addEventListener('keydown',e=>{if(e.key==='Enter'){S.q=e.target.value;S.pg=1;go('inbox')}});
const sub={lf(){const e=$('#em').value.trim(),a=fe('em',mailOk(e)?'':'Enter a valid email address.'),b=fe('pw',$('#pw').value.length>=6?'':'Password must be at least 6 characters.');if(a&&b){if(e.includes('sarah')||e.includes('customer')||S.role==='customer'){S.role='customer';$('#um-btn').innerHTML='Sarah Chen &#9662;'}else if(e.includes('marcus')||e.includes('agent')||e.includes('staff')||S.role==='staff'){S.role='staff';$('#um-btn').innerHTML='Marcus Vance &#9662;'}else{S.role='admin';$('#um-btn').innerHTML='Priya Nair &#9662;'}$$('[data-act=role]').forEach(btn=>btn.classList.toggle('on',btn.dataset.r===S.role));$('#login').hidden=true;$('#app').hidden=false;go('dash')}},
nf(){const e=$('#ce').value.trim(),s=$('#cs2').value.trim(),d=$('#cd').value.trim(),r=[fe('ce',mailOk(e)?'':'Enter a valid customer email.'),fe('cs2',s.length>=5?'':'Subject needs at least 5 characters.'),fe('cd',d.length>=10?'':'Describe the issue in at least 10 characters.')];if(r.includes(false))return;
let i=custs.findIndex(c=>c.e===e);if(i<0){custs.push({n:e.split('@')[0],e,co:'New customer'});i=custs.length-1}
const t={id:'NX-'+(1001+tix.length),s,c:i,cat:$('#cc').value,pri:$('#cp').value,st:'Open',ag:-1,age:0,msgs:[{w:'c',t:d,tm:'just now'}],log:['Ticket created by agent']};tix.unshift(t);go('tk',t.id);toast(t.id+' created (mock)')},
sf(){toast('Settings saved (mock, not stored)')}};
document.addEventListener('submit',e=>{e.preventDefault();const f=sub[e.target.id];if(f)f()});
